apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: mongo-pvc
spec:
     storageClassName: cloud-ssd
     accessModes:
         - ReadWriteOnce
     resources:
         requests:
           storage: 12Gi
 
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: cloud-ssd 
provisioner: kubernetes.io/aws-ebs
parameters:
    type: gp2
reclaimPolicy: Retain
mountOptions:
      - debug
kubeletExtraArgs:
       cloud-provider: "aws"
volumeBindingMode: Immediate

           
